### ISSUE TITLE
PrescriptionCount

### ISSUE THREAD

**Issue by DarraghFahey** [emmettcowan/Software_With_Test_Group_A#7]
@KrystianGab I noticed in the Prescription class setPrescription() is only set when prescriptionCount<=3 but, it will always be less than 3 as you initialise it to 0 and its not passed in to the constructor. So when a prescription object is called the count doesn't matter as its written now, it cant ever be above 3

**Comment by KrystianGab** [comment]
As discussed during the meeting, prescriptionCount will not be a feature in the final product due to the structure of our DB. I will remove it from the code.
